<a href="https://colab.research.google.com/github/GauriMittal24/AI-lab-assignments/blob/main/AI_lab_Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
with open('log_file.log','r') as log_file:
  log_data=log_file.readlines()

log_data

['87.116.74.253 - - [28/Feb/2022:14:04:44 +0200] "POST /wp-admin/admin-ajax.php HTTP/2.0" 200 47 "https://nargile.bg/wp-admin/admin.php?page=wc-settings" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36"\n',
 '91.196.124.220 - - [28/Feb/2022:14:04:47 +0200] "POST /wp-cron.php?doing_wp_cron=1646049887.2476160526275634765625 HTTP/1.1" 200 - "https://nargile.bg/wp-cron.php?doing_wp_cron=1646049887.2476160526275634765625" "WordPress/5.9.1; https://nargile.bg"\n',
 '91.196.124.220 - - [28/Feb/2022:14:06:45 +0200] "POST /wp-cron.php?doing_wp_cron=1646050005.3947830200195312500000 HTTP/1.1" 200 - "https://nargile.bg/wp-cron.php?doing_wp_cron=1646050005.3947830200195312500000" "WordPress/5.9.1; https://nargile.bg"\n',
 '87.116.74.253 - - [28/Feb/2022:14:06:44 +0200] "POST /wp-admin/admin-ajax.php HTTP/2.0" 200 47 "https://nargile.bg/wp-admin/admin.php?page=wc-settings" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) App

In [ ]:
# Sanitizing and structuring the data
import re

# Define a function to parse log entries
def parse_log_entry(log_entry):
    # Use regular expressions to extract relevant information
    pattern = r'(\S+) - - \[(.*?)\] "(.*?)" (\d+) (\d+) "(.*?)" "(.*?)"'
    match = re.match(pattern, log_entry)
    if match:
        ip_address = match.group(1)
        timestamp = match.group(2)
        request_info = match.group(3)
        http_status_code = int(match.group(4))
        content_length = int(match.group(5))
        referer = match.group(6)
        user_agent = match.group(7)

        # Return the extracted data as a dictionary
        return {
            "IP Address": ip_address,
            "Timestamp": timestamp,
            "Request Info": request_info,
            "HTTP Status Code": http_status_code,
            "Content Length": content_length,
            "Referer": referer,
            "User-Agent": user_agent
        }
    else:
        return None

# Read the log file
log_entries = []
with open('log_file.log', 'r') as log_file:
    for line in log_file:
        log_entry = line.strip()
        sanitized_entry = parse_log_entry(log_entry)
        if sanitized_entry:
            log_entries.append(sanitized_entry)

# Now, log_entries contains the sanitized log data in a structured format
# You can perform various analyses on this data using libraries like pandas


In [ ]:
# Converting list of dictionaries to dataframe
import pandas as pd
df=pd.DataFrame(log_entries)

In [ ]:
df.head(10)

IP Address                   Timestamp  \
0  87.116.74.253  28/Feb/2022:14:04:44 +0200   
1  87.116.74.253  28/Feb/2022:14:06:44 +0200   
2   66.249.70.57  28/Feb/2022:14:06:46 +0200   
3   66.249.70.59  28/Feb/2022:14:06:51 +0200   
4   66.249.70.57  28/Feb/2022:14:06:52 +0200   
5   66.249.70.59  28/Feb/2022:14:06:53 +0200   
6   66.249.70.59  28/Feb/2022:14:06:54 +0200   
7  157.55.39.141  28/Feb/2022:14:06:54 +0200   
8   66.249.70.57  28/Feb/2022:14:06:55 +0200   
9   66.249.70.57  28/Feb/2022:14:06:56 +0200   

                                        Request Info  HTTP Status Code  \
0             POST /wp-admin/admin-ajax.php HTTP/2.0               200   
1             POST /wp-admin/admin-ajax.php HTTP/2.0               200   
2               GET /category/alpaca-bowls/ HTTP/1.1               200   
3  GET /wp-content/themes/woodmart/css/parts/widg...               200   
4  GET /wp-content/themes/woodmart/css/parts/opt-...               200   
5  GET /wp-content/themes/woodmart/css/parts/head...               200   
6  GET /wp-content/themes/woodmart/css/parts/int-...               200   
7  GET /wp-content/uploads/2021/06/maklaud-endo-i...               200   
8  GET /wp-content/plugins/js_composer/assets/lib...               200   
9  GET /wp-includes/js/dist/vendor/regenerator-ru...               200   

   Content Length                                            Referer  \
0              47  https://nargile.bg/wp-admin/admin.php?page=wc-...   
1              47  https://nargile.bg/wp-admin/admin.php?page=wc-...   
2          262929                                                  -   
3             992          https://nargile.bg/category/alpaca-bowls/   
4             308          https://nargile.bg/category/alpaca-bowls/   
5             793          https://nargile.bg/category/alpaca-bowls/   
6            1241          https://nargile.bg/category/alpaca-bowls/   
7          104824                                                  -   
8           56425          https://nargile.bg/category/alpaca-bowls/   
9            6494          https://nargile.bg/category/alpaca-bowls/   

                                          User-Agent  
0  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  
1  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  
2  Mozilla/5.0 (compatible; Googlebot/2.1; +http:...  
3  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...  
4  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...  
5  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...  
6  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...  
7  Mozilla/5.0 (compatible; bingbot/2.0; +http://...  
8  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...  
9  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...

In [ ]:
# Converting timestamp to standard date time format
df['Timestamp']=pd.to_datetime((df['Timestamp']),format='%d/%b/%Y:%H:%M:%S %z')



In [ ]:
# columns of data
df.columns

Index(['IP Address', 'Timestamp', 'Request Info', 'HTTP Status Code',
       'Content Length', 'Referer', 'User-Agent'],
      dtype='object')

In [ ]:
df.head()

IP Address                 Timestamp  \
0  87.116.74.253 2022-02-28 14:04:44+02:00   
1  87.116.74.253 2022-02-28 14:06:44+02:00   
2   66.249.70.57 2022-02-28 14:06:46+02:00   
3   66.249.70.59 2022-02-28 14:06:51+02:00   
4   66.249.70.57 2022-02-28 14:06:52+02:00   

                                        Request Info  HTTP Status Code  \
0             POST /wp-admin/admin-ajax.php HTTP/2.0               200   
1             POST /wp-admin/admin-ajax.php HTTP/2.0               200   
2               GET /category/alpaca-bowls/ HTTP/1.1               200   
3  GET /wp-content/themes/woodmart/css/parts/widg...               200   
4  GET /wp-content/themes/woodmart/css/parts/opt-...               200   

   Content Length                                            Referer  \
0              47  https://nargile.bg/wp-admin/admin.php?page=wc-...   
1              47  https://nargile.bg/wp-admin/admin.php?page=wc-...   
2          262929                                                  -   
3             992          https://nargile.bg/category/alpaca-bowls/   
4             308          https://nargile.bg/category/alpaca-bowls/   

                                          User-Agent  
0  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  
1  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  
2  Mozilla/5.0 (compatible; Googlebot/2.1; +http:...  
3  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...  
4  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...

In [ ]:
# Adding new columns in dataframe to do predictions
# Extract datetime features
df['Hour'] = df['Timestamp'].dt.hour
df['DayOfWeek'] = df['Timestamp'].dt.dayofweek
df['Month'] = df['Timestamp'].dt.month


# Create a session identifier
df['SessionID'] = df.groupby('IP Address')['Timestamp'].diff().gt(pd.Timedelta('30min')).cumsum()

# Categorize requests into types
df['RequestType'] = df['Request Info'].apply(lambda x: x.split()[0] if isinstance(x, str) else '')

# Extract features from URLs
df['Endpoint'] = df['Request Info'].apply(lambda x: x.split()[1] if isinstance(x, str) else '')

# Add an error indicator
df['Error'] = df['HTTP Status Code'].apply(lambda x: 1 if x >= 400 else 0)

# Identify bots
df['IsBot'] = df['User-Agent'].str.contains('bot', case=False)

# Calculate page load time
df['PageLoadTime'] = df.groupby('SessionID')['Timestamp'].diff()

# Display the updated DataFrame
print(df.head())


      IP Address                 Timestamp  \
0  87.116.74.253 2022-02-28 14:04:44+02:00   
1  87.116.74.253 2022-02-28 14:06:44+02:00   
2   66.249.70.57 2022-02-28 14:06:46+02:00   
3   66.249.70.59 2022-02-28 14:06:51+02:00   
4   66.249.70.57 2022-02-28 14:06:52+02:00   

                                        Request Info  HTTP Status Code  \
0             POST /wp-admin/admin-ajax.php HTTP/2.0               200   
1             POST /wp-admin/admin-ajax.php HTTP/2.0               200   
2               GET /category/alpaca-bowls/ HTTP/1.1               200   
3  GET /wp-content/themes/woodmart/css/parts/widg...               200   
4  GET /wp-content/themes/woodmart/css/parts/opt-...               200   

   Content Length                                            Referer  \
0              47  https://nargile.bg/wp-admin/admin.php?page=wc-...   
1              47  https://nargile.bg/wp-admin/admin.php?page=wc-...   
2          262929                                             

In [ ]:

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score


In [ ]:
# Select relevant columns for analysis
columns_to_include = ['PageLoadTime', 'Hour', 'DayOfWeek', 'Month', 'Error', 'IsBot']

for target_variable in columns_to_include:
    # Store the target variable separately
    y = df[target_variable].copy()

    # Create a new DataFrame with selected columns
    df_regression = df[['Hour', 'DayOfWeek', 'Month', 'Error', 'IsBot']].copy()

    # Drop rows with missing values
    df_regression.dropna(inplace=True)

    # Convert datetime to numeric (seconds)
    df_regression['PageLoadTime'] = df['PageLoadTime'].dt.total_seconds()

    # Impute missing values in X and y
    df_regression.fillna(df_regression.mean(), inplace=True)
    y.fillna(y.mean(), inplace=True)

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(
        df_regression.drop(target_variable, axis=1),
        y,
        test_size=0.2,
        random_state=42
    )

    # Create and train the linear regression model
    model = LinearRegression()
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Convert y_test to numeric format if it's in datetime format
    if y_test.dtype == '<m8[ns]':
        y_test = y_test.dt.total_seconds()

    # Evaluate the model
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)



    print(f'\nTarget Variable: {target_variable}')

    print(f'Mean Squared Error: {mse}')
    print(f'R-squared: {r2}')



Target Variable: PageLoadTime
Mean Squared Error: 2.177819425577251e+18
R-squared: -3.950339593355506e+16

Target Variable: Hour
Mean Squared Error: 0.0
R-squared: 1.0

Target Variable: DayOfWeek
Mean Squared Error: 0.0
R-squared: 1.0

Target Variable: Month
Mean Squared Error: 0.0
R-squared: 1.0

Target Variable: Error
Mean Squared Error: 0.013834029714383007
R-squared: 0.06772063759628444

Target Variable: IsBot
Mean Squared Error: 0.007867004595470713
R-squared: -0.05227157625404022


In [ ]:

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# Selecting the target variable and features
target_variable = 'Error'
features = ['Hour', 'DayOfWeek', 'Month', 'IsBot']

# Creating a new DataFrame with selected columns
df_logistic = df[[target_variable] + features].copy()

# Drop rows with missing values
df_logistic.dropna(inplace=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_logistic.drop(target_variable, axis=1),
    df_logistic[target_variable],
    test_size=0.2,
    random_state=42
)

# Create and train the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.9849340866290018
Confusion Matrix:
[[523   0]
 [  8   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       523
           1       0.00      0.00      0.00         8

    accuracy                           0.98       531
   macro avg       0.49      0.50      0.50       531
weighted avg       0.97      0.98      0.98       531



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:


# Selecting the target variable and features
target_variable = 'IsBot'
features = ['Hour', 'DayOfWeek', 'Month', 'Error', 'Content Length']

# Creating a new DataFrame with selected columns
df_logistic = df[[target_variable] + features].copy()

# Drop rows with missing values
df_logistic.dropna(inplace=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_logistic.drop(target_variable, axis=1),
    df_logistic[target_variable],
    test_size=0.2,
    random_state=42
)

# Create and train the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.9887005649717514
Confusion Matrix:
[[525   2]
 [  4   0]]
Classification Report:
              precision    recall  f1-score   support

       False       0.99      1.00      0.99       527
        True       0.00      0.00      0.00         4

    accuracy                           0.99       531
   macro avg       0.50      0.50      0.50       531
weighted avg       0.98      0.99      0.99       531



In [ ]:
from sklearn.tree import DecisionTreeClassifier


# Assuming df is your DataFrame containing the web server log data

# Selecting the target variable and features
target_variable = 'IsBot'
features = ['Hour', 'DayOfWeek', 'Month', 'Error', 'Content Length']

# Creating a new DataFrame with selected columns
df_decision_tree = df[[target_variable] + features].copy()

# Drop rows with missing values
df_decision_tree.dropna(inplace=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_decision_tree.drop(target_variable, axis=1),
    df_decision_tree[target_variable],
    test_size=0.2,
    random_state=42
)

# Create and train the decision tree model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.992467043314501
Confusion Matrix:
[[525   2]
 [  2   2]]
Classification Report:
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       527
        True       0.50      0.50      0.50         4

    accuracy                           0.99       531
   macro avg       0.75      0.75      0.75       531
weighted avg       0.99      0.99      0.99       531



In [ ]:


# Assuming df is your DataFrame containing the web server log data

# Selecting the target variable and features
target_variable = 'Error'
features = ['Hour', 'DayOfWeek', 'Month', 'IsBot', 'Content Length']

# Creating a new DataFrame with selected columns
df_decision_tree = df[[target_variable] + features].copy()

# Drop rows with missing values
df_decision_tree.dropna(inplace=True)

# Convert 'IsBot' column to numeric if it's boolean
df_decision_tree['IsBot'] = df_decision_tree['IsBot'].astype(int)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_decision_tree.drop(target_variable, axis=1),
    df_decision_tree[target_variable],
    test_size=0.2,
    random_state=42
)

# Create and train the decision tree model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.9962335216572504
Confusion Matrix:
[[521   2]
 [  0   8]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       523
           1       0.80      1.00      0.89         8

    accuracy                           1.00       531
   macro avg       0.90      1.00      0.94       531
weighted avg       1.00      1.00      1.00       531



In [ ]:


from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# Assuming df is your DataFrame containing the web server log data

# Selecting the target variable and features
target_variable = 'IsBot'
features = ['Hour', 'DayOfWeek', 'Month', 'Error', 'Content Length']

# Creating a new DataFrame with selected columns
df_svm = df[[target_variable] + features].copy()

# Drop rows with missing values
df_svm.dropna(inplace=True)

# Convert 'IsBot' column to numeric
df_svm['IsBot'] = df_svm['IsBot'].astype(int)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_svm.drop(target_variable, axis=1),
    df_svm[target_variable],
    test_size=0.2,
    random_state=42
)

# Standardize the features (important for SVM)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create and train the SVM model
model = SVC(kernel='linear', C=1)  # You can adjust the kernel and C parameter
model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.992467043314501
Confusion Matrix:
[[527   0]
 [  4   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       527
           1       0.00      0.00      0.00         4

    accuracy                           0.99       531
   macro avg       0.50      0.50      0.50       531
weighted avg       0.98      0.99      0.99       531



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:

# Assuming df is your DataFrame containing the web server log data

# Selecting the target variable and features
target_variable = 'Error'
features = ['Hour', 'DayOfWeek', 'Month', 'IsBot', 'Content Length']

# Creating a new DataFrame with selected columns
df_svm = df[[target_variable] + features].copy()

# Drop rows with missing values
df_svm.dropna(inplace=True)

# Convert 'IsBot' column to numeric
df_svm['IsBot'] = df_svm['IsBot'].astype(int)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_svm.drop(target_variable, axis=1),
    df_svm[target_variable],
    test_size=0.2,
    random_state=42
)

# Standardize the features (important for SVM)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create and train the SVM model
model = SVC(kernel='linear', C=1)  # You can adjust the kernel and C parameter
model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.9849340866290018
Confusion Matrix:
[[523   0]
 [  8   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       523
           1       0.00      0.00      0.00         8

    accuracy                           0.98       531
   macro avg       0.49      0.50      0.50       531
weighted avg       0.97      0.98      0.98       531



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.naive_bayes import GaussianNB

# Assuming df is your DataFrame containing the web server log data

# Selecting the target variable and features
target_variable = 'IsBot'  # You can change this based on your dataset
features = ['Hour', 'DayOfWeek', 'Month', 'Error', 'Content Length']

# Creating a new DataFrame with selected columns
df_naive_bayes = df[[target_variable] + features].copy()

# Drop rows with missing values
df_naive_bayes.dropna(inplace=True)

# Convert 'IsBot' column to numeric
df_naive_bayes['IsBot'] = df_naive_bayes['IsBot'].astype(int)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_naive_bayes.drop(target_variable, axis=1),
    df_naive_bayes[target_variable],
    test_size=0.2,
    random_state=42
)

# Standardize the features (important for some Naive Bayes models)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create and train the Gaussian Naive Bayes model
model = GaussianNB()
model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.9661016949152542
Confusion Matrix:
[[512  15]
 [  3   1]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       527
           1       0.06      0.25      0.10         4

    accuracy                           0.97       531
   macro avg       0.53      0.61      0.54       531
weighted avg       0.99      0.97      0.98       531



In [ ]:

# Selecting the target variable and features
target_variable = 'Error'
features = ['Hour', 'DayOfWeek', 'Month', 'IsBot', 'Content Length']

# Creating a new DataFrame with selected columns
df_naive_bayes = df[[target_variable] + features].copy()

# Drop rows with missing values
df_naive_bayes.dropna(inplace=True)

# Convert 'Error' column to numeric
df_naive_bayes['Error'] = df_naive_bayes['Error'].astype(int)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_naive_bayes.drop(target_variable, axis=1),
    df_naive_bayes[target_variable],
    test_size=0.2,
    random_state=42
)

# Create and train the Gaussian Naive Bayes model
model = GaussianNB()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.9661016949152542
Confusion Matrix:
[[513  10]
 [  8   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       523
           1       0.00      0.00      0.00         8

    accuracy                           0.97       531
   macro avg       0.49      0.49      0.49       531
weighted avg       0.97      0.97      0.97       531



In [ ]:
from sklearn.naive_bayes import MultinomialNB

# Selecting the target variable and features
target_variable = 'HTTP Status Code'
features = ['Hour', 'DayOfWeek', 'Month', 'IsBot', 'Content Length', 'Error']

# Creating a new DataFrame with selected columns
df_naive_bayes = df[[target_variable] + features].copy()

# Drop rows with missing values
df_naive_bayes.dropna(inplace=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_naive_bayes.drop(target_variable, axis=1),
    df_naive_bayes[target_variable],
    test_size=0.2,
    random_state=42
)

# Create and train the Multinomial Naive Bayes model
model = MultinomialNB()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.832391713747646
Confusion Matrix:
[[435   8  47  33   0]
 [  0   0   0   0   0]
 [  0   0   6   0   0]
 [  0   0   0   1   0]
 [  0   0   1   0   0]]
Classification Report:
              precision    recall  f1-score   support

         200       1.00      0.83      0.91       523
         403       0.00      0.00      0.00         0
         404       0.11      1.00      0.20         6
         406       0.03      1.00      0.06         1
         500       0.00      0.00      0.00         1

    accuracy                           0.83       531
   macro avg       0.23      0.57      0.23       531
weighted avg       0.99      0.83      0.90       531



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [ ]:

from sklearn.feature_extraction.text import TfidfVectorizer


# Assuming df is your DataFrame containing the web server log data

# Selecting relevant columns for the TF-IDF model
text_columns = ['Request Info', 'Referer', 'User-Agent']

# Creating a new DataFrame with selected columns
df_tfidf = df[text_columns].copy()

# Concatenate the selected text columns into a single column
df_tfidf['Combined_Text'] = df_tfidf.apply(lambda row: ' '.join(row.values.astype(str)), axis=1)

# Extracting the target variable
target_variable = 'IsBot'

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_tfidf['Combined_Text'],
    df[target_variable],
    test_size=0.2,
    random_state=42
)

# Create and fit the TF-IDF vectorizer on the training data
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

# Transform the test data using the same vectorizer
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Create and train a model (e.g., Logistic Regression) on the TF-IDF features
model = LogisticRegression()
model.fit(X_train_tfidf, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_tfidf)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.9981167608286252
Confusion Matrix:
[[527   0]
 [  1   3]]
Classification Report:
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       527
        True       1.00      0.75      0.86         4

    accuracy                           1.00       531
   macro avg       1.00      0.88      0.93       531
weighted avg       1.00      1.00      1.00       531



In [ ]:




# Selecting relevant columns for the TF-IDF model
text_columns = ['Endpoint']

# Creating a new DataFrame with selected columns
df_tfidf = df[['IsBot'] + text_columns].copy()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df_tfidf['Endpoint'],
    df_tfidf['IsBot'],
    test_size=0.2,
    random_state=42
)

# Create and fit the TF-IDF vectorizer on the training data
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

# Transform the test data using the same vectorizer
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Create and train a model (e.g., Logistic Regression) on the TF-IDF features
model = LogisticRegression()
model.fit(X_train_tfidf, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_tfidf)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.992467043314501
Confusion Matrix:
[[527   0]
 [  4   0]]
Classification Report:
              precision    recall  f1-score   support

       False       0.99      1.00      1.00       527
        True       0.00      0.00      0.00         4

    accuracy                           0.99       531
   macro avg       0.50      0.50      0.50       531
weighted avg       0.98      0.99      0.99       531



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:

# Assuming df is your DataFrame containing the web server log data

# Selecting relevant columns for the TF-IDF model
text_columns = ['Error']

# Creating a new DataFrame with selected columns
df_tfidf = df[['IsBot'] + text_columns].copy()

# Convert non-string values in 'Error' column to strings
df_tfidf['Error'] = df_tfidf['Error'].astype(str)

# Fill missing values in the 'Error' column with an empty string
df_tfidf['Error'].fillna('', inplace=True)

# Check if there is at least one non-stop word in the text
df_tfidf['ContainsText'] = df_tfidf['Error'].apply(lambda x: any(word.isalpha() for word in x.split()))

# Filter out rows with no text content
df_tfidf = df_tfidf[df_tfidf['ContainsText']]

# Check if there are samples left after filtering
if df_tfidf.empty:
    print("No samples with text content found. Adjust your filtering criteria.")
else:
    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(
        df_tfidf['Error'],
        df_tfidf['IsBot'],
        test_size=0.2,
        random_state=42
    )

    # Create and fit the TF-IDF vectorizer on the training data
    tfidf_vectorizer = TfidfVectorizer()
    X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

    # Transform the test data using the same vectorizer
    X_test_tfidf = tfidf_vectorizer.transform(X_test)

    # Create and train a model (e.g., Logistic Regression) on the TF-IDF features
    model = LogisticRegression()
    model.fit(X_train_tfidf, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test_tfidf)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)

    print(f'Accuracy: {accuracy}')
    print(f'Confusion Matrix:\n{conf_matrix}')
    print(f'Classification Report:\n{classification_rep}')


No samples with text content found. Adjust your filtering criteria.


In [ ]:
import numpy as np

from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk
import numpy as np  # Add this line to import NumPy
nltk.download('punkt')

# Assuming df is your DataFrame containing the web server log data

# Selecting relevant columns for the Word2Vec model
text_columns = ['Error']

# Creating a new DataFrame with selected columns
df_word2vec = df[['IsBot'] + text_columns].copy()

# Convert non-string values in 'Error' column to strings
df_word2vec['Error'] = df_word2vec['Error'].astype(str)

# Fill missing values in the 'Error' column with an empty string
df_word2vec['Error'].fillna('', inplace=True)

# Tokenize the text
df_word2vec['Error'] = df_word2vec['Error'].apply(word_tokenize)

# Check if there is at least one word in the text
df_word2vec['ContainsText'] = df_word2vec['Error'].apply(lambda x: len(x) > 0)

# Filter out rows with no text content
df_word2vec = df_word2vec[df_word2vec['ContainsText']]

# Check if there are samples left after filtering
if df_word2vec.empty:
    print("No samples with text content found. Adjust your filtering criteria.")
else:
    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(
        df_word2vec['Error'],
        df_word2vec['IsBot'],
        test_size=0.2,
        random_state=42
    )

    # Train a Word2Vec model on the training data
    model = Word2Vec(sentences=X_train, vector_size=100, window=5, min_count=1, workers=4)

    # Function to average word vectors and create document vectors
    def document_vector(model, doc):
        return np.mean([model.wv[word] for word in doc if word in model.wv], axis=0)

    # Apply the function to your training and testing data
    X_train_word2vec = [document_vector(model, doc) for doc in X_train]
    X_test_word2vec = [document_vector(model, doc) for doc in X_test]

    # Create and train a model (e.g., Logistic Regression) on the Word2Vec features
    model = LogisticRegression()
    model.fit(X_train_word2vec, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test_word2vec)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)

    print(f'Accuracy: {accuracy}')
    print(f'Confusion Matrix:\n{conf_matrix}')
    print(f'Classification Report:\n{classification_rep}')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Accuracy: 0.992467043314501
Confusion Matrix:
[[527   0]
 [  4   0]]
Classification Report:
              precision    recall  f1-score   support

       False       0.99      1.00      1.00       527
        True       0.00      0.00      0.00         4

    accuracy                           0.99       531
   macro avg       0.50      0.50      0.50       531
weighted avg       0.98      0.99      0.99       531



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
!python -m spacy download en_core_web_md


2023-11-11 10:33:47.208431: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-11 10:33:47.208513: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-11 10:33:47.208556: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-11 10:33:47.217925: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-11 10:33:48.456707: W tensorflow/compiler/

In [ ]:

import spacy


# Assuming df is your DataFrame containing the web server log data

# Selecting relevant columns for the GloVe model
text_columns = ['Error']

# Creating a new DataFrame with selected columns
df_glove = df[['IsBot'] + text_columns].copy()

# Convert non-string values in 'Error' column to strings
df_glove['Error'] = df_glove['Error'].astype(str)

# Fill missing values in the 'Error' column with an empty string
df_glove['Error'].fillna('', inplace=True)

# Load the spacy model with GloVe embeddings
nlp = spacy.load('en_core_web_md')

# Function to calculate the document vector using GloVe embeddings
def document_vector(doc):
    # Remove stop words and average the word vectors
    vectors = [word.vector for word in doc if word.is_alpha and not word.is_stop]
    if vectors:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(300)  # Return a vector of zeros if no valid words

# Apply the function to your dataset
df_glove['Error'] = df_glove['Error'].apply(lambda x: document_vector(nlp(x)))

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    list(df_glove['Error']),
    df_glove['IsBot'],
    test_size=0.2,
    random_state=42
)

# Create and train a model (e.g., Logistic Regression) on the GloVe features
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.992467043314501
Confusion Matrix:
[[527   0]
 [  4   0]]
Classification Report:
              precision    recall  f1-score   support

       False       0.99      1.00      1.00       527
        True       0.00      0.00      0.00         4

    accuracy                           0.99       531
   macro avg       0.50      0.50      0.50       531
weighted avg       0.98      0.99      0.99       531



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import nltk
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('wordnet')

# Sample function to get part of speech for WordNet lemmatizer
def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"N": wordnet.NOUN, "V": wordnet.VERB, "R": wordnet.ADV, "J": wordnet.ADJ}
    return tag_dict.get(tag, wordnet.NOUN)

# Sample function for lemmatizing text using NLTK
def lemmatize_text_nltk(text):
    lemmatizer = WordNetLemmatizer()
    try:
        tokens = word_tokenize(str(text))  # Ensure the input is converted to a string
        lemmatized_tokens = [lemmatizer.lemmatize(token, get_wordnet_pos(token)) for token in tokens]
        return ' '.join(lemmatized_tokens)
    except Exception as e:
        print(f"Error processing text: {text}, Error: {e}")
        return ''  # Return an empty string or handle missing values based on your requirements

# Apply lemmatization to a specific column in your DataFrame
df['LemmatizedColumn'] = df['Error'].apply(lemmatize_text_nltk)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Streaming output truncated to the last 5000 lines.
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

Error processing text: 0, Error: 
**********************************************************************
  Resource averaged_perceptron_tagger not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'

Epoch 1/10
67/67 [==============================] - 3s 13ms/step - loss: 0.3371 - accuracy: 0.9845 - val_loss: 0.0456 - val_accuracy: 0.9925
Epoch 2/10
67/67 [==============================] - 0s 5ms/step - loss: 0.0755 - accuracy: 0.9845 - val_loss: 0.0433 - val_accuracy: 0.9925
Epoch 3/10
67/67 [==============================] - 0s 4ms/step - loss: 0.0750 - accuracy: 0.9845 - val_loss: 0.0419 - val_accuracy: 0.9925
Epoch 4/10
67/67 [==============================] - 0s 5ms/step - loss: 0.0749 - accuracy: 0.9845 - val_loss: 0.0460 - val_accuracy: 0.9925
Epoch 5/10
67/67 [==============================] - 0s 5ms/step - loss: 0.0749 - accuracy: 0.9845 - val_loss: 0.0415 - val_accuracy: 0.9925
Epoch 6/10
67/67 [==============================] - 0s 5ms/step - loss: 0.0751 - accuracy: 0.9845 - val_loss: 0.0418 - val_accuracy: 0.9925
Epoch 7/10
67/67 [==============================] - 0s 5ms/step - loss: 0.0747 - accuracy: 0.9845 - val_loss: 0.0439 - val_accuracy: 0.9925
Epoch 8/10
67/67 [=